### PR TITLE
Delete .github/workflows/cr.yml

### PR DESCRIPTION
**Pull request by The-Code-Monkey**

### CODE REVIEW

**Comment by noodles-4liph** [comment]
Are we sure we won't want to use this in the future? What benefit do we derive from removing this?

**Comment by The-Code-Monkey** [comment]
If we want to use it in the future I can add it back but for now seeing as it errors cause we aren't using it. If we remove it the bot can then keep all packages up to date

**Review by noodles-4liph — APPROVED** [review]

**Comment by noodles-4liph** [comment]
Approved.

**Review by PrasadBroo — COMMENTED** [review]
i havent worked with github workflows so idont know what to say :)

**Comment by noodles-4liph** [comment]
> i havent worked with github workflows so idont know what to say :)

We just need two people to approve the change. This is just a safe guard.

**Pull request merged**
